[project]
name = "mechaparabellum"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fire",
    "lxml>=6.0.0",
    "notebook>=7.4.4",
    "packaging>=25.0",
    "rich",
    "stringcase>=1.2.0",
]
